import { PATH_COMMAND } from '../types';
import { PATH_SEGMENT_TYPE } from '../types';

export const TYPE_TO_TAG = new Map<PATH_SEGMENT_TYPE, PATH_COMMAND>([
    [PATH_SEGMENT_TYPE.ARC_ABS, PATH_COMMAND.A],
    [PATH_SEGMENT_TYPE.ARC_REL, PATH_COMMAND.a],
    [PATH_SEGMENT_TYPE.CLOSEPATH, PATH_COMMAND.z],
    [PATH_SEGMENT_TYPE.CURVETO_CUBIC_ABS, PATH_COMMAND.C],
    [PATH_SEGMENT_TYPE.CURVETO_CUBIC_REL, PATH_COMMAND.c],
    [PATH_SEGMENT_TYPE.CURVETO_CUBIC_SMOOTH_ABS, PATH_COMMAND.S],
    [PATH_SEGMENT_TYPE.CURVETO_CUBIC_SMOOTH_REL, PATH_COMMAND.s],
    [PATH_SEGMENT_TYPE.CURVETO_QUADRATIC_ABS, PATH_COMMAND.Q],
    [PATH_SEGMENT_TYPE.CURVETO_QUADRATIC_REL, PATH_COMMAND.q],
    [PATH_SEGMENT_TYPE.CURVETO_QUADRATIC_SMOOTH_ABS, PATH_COMMAND.T],
    [PATH_SEGMENT_TYPE.CURVETO_QUADRATIC_SMOOTH_REL, PATH_COMMAND.t],
    [PATH_SEGMENT_TYPE.LINETO_ABS, PATH_COMMAND.L],
    [PATH_SEGMENT_TYPE.LINETO_HORIZONTAL_REL, PATH_COMMAND.H],
    [PATH_SEGMENT_TYPE.LINETO_HORIZONTAL_ABS, PATH_COMMAND.h],
    [PATH_SEGMENT_TYPE.LINETO_REL, PATH_COMMAND.l],
    [PATH_SEGMENT_TYPE.LINETO_VERTICAL_ABS, PATH_COMMAND.V],
    [PATH_SEGMENT_TYPE.LINETO_VERTICAL_REL, PATH_COMMAND.v],
    [PATH_SEGMENT_TYPE.MOVETO_ABS, PATH_COMMAND.M],
    [PATH_SEGMENT_TYPE.MOVETO_REL, PATH_COMMAND.m]
]);
